service_application_package/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ProjectForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Publish')

service_application_package/projects/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from service_application_package import db
from service_application_package.models import Project
from service_application_package.projects.forms import ProjectForm
from service_application_package.models import Story
import math

projects = Blueprint('projects', __name__)


@projects.route("/project/new", methods=['GET', 'POST'])
@login_required
def new_project():
    form = ProjectForm()
    if form.validate_on_submit():
        project = Project(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(project)
        db.session.commit()
        flash('Your project has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_project.html', title='New Project',
                           form=form, legend='New Project')

@projects.route("/projects/all")
def list_projects():
    form = ProjectForm()
    projects = Project.query.all()
    doneCount = 0
    total = 0
    doneList = []

    for proj in projects:
        stories = Story.query.filter_by(project_id = proj.id)
        for sto in stories:
            if sto.status == 'done':
                doneCount += 1
            total += 1
        if(total == 0):
            doneList.append(0)
        else:
            percentDone = (doneCount / total) * 100
            doneList.append(math.ceil(percentDone))
        doneCount = 0
        total = 0
        
    return render_template('projects_all.html', 
                           form=form, title='project', legend="New Project", projects=projects, doneList = doneList)

@projects.route("/project/<int:project_id>")
def project(project_id):
    project = Project.query.get_or_404(project_id)
    return render_template('project.html', title=project.title, project=project)


@projects.route("/project/<int:project_id>/update", methods=['GET', 'POST'])
@login_required
def update_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.author != current_user:
        abort(403)
    form = ProjectForm()
    if form.validate_on_submit():
        project.title = form.title.data
        project.content = form.content.data
        db.session.commit()
        flash('Your project has been updated!', 'success')
        return redirect(url_for('projects.project', project_id=project.id))
    elif request.method == 'GET':
        form.title.data = project.title
        form.content.data = project.content
    return render_template('create_project.html', title='Update Project',
                           form=form, legend='Update Project')


@projects.route("/project/<int:project_id>/delete", methods=['POST'])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.author != current_user:
        abort(403)
    db.session.delete(project)
    db.session.commit()
    flash('Your project has been deleted!', 'success')
    return redirect(url_for('main.home'))

service_application_package/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required
from service_application_package import db, bcrypt
from service_application_package.models import User, Project
from service_application_package.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from service_application_package.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # session save username
            session.permanent=True
            session['username'] = user.username # save username to session
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_projects(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    projects = Project.query.filter_by(author=user)\
        .order_by(Project.date_projected.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_projects.html', projects=projects, user=user)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

service_application_package/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

service_application_package/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

service_application_package/templates/create_project.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

service_application_package/templates/create_requirement.html
{% extends "layout.html" %}

{% block content %}
{% if current_user.is_authenticated %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% else %}
    <div class="alert alert-info">Please login to edit projects</div>
{% endif %}

{% endblock content %}

service_application_package/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div id="home-content" class="container my-auto mx-auto py-3 px-1">

    <h5>The Project Management Service App enables users to collaborate with others displaying requirements, issues, and even a chat!</h5>

    <div class="card-deck mb-3 py-5 px-auto w-auto">
        


</div>
    {% for project in projects.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <small class="text-muted">{{ project.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('projects.project', project_id=project.id) }}">{{ project.title }}</a></h2>
            <p class="article-content">{{ project.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in projects.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if projects.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

service_application_package/templates/issues_all.html
{% extends "layout.html" %}
{% block content %}
  <div class="panel panel-default">
  <h2 class="panel-heading" style="padding-left: 15px">Issue List</h2>
    <div style="display: inline-block">
      <nav class="navbar navbar-light bg-light">
        <form class="form-inline"  action = "{{ url_for('issues.issue_search') }}" method="get">
          <input class="form-control mr-sm-2"  placeholder="Search"  name = "Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </nav>
    </div>
    <div style="display: inline-block; float: right">
        <a role="button"  class="btn btn-outline-info" style = "float: right;" href="{{ url_for('issues.new_issue') }}">New Issue</a>
    </div>

<style>
body{
    counter-reset: num;
}

li:before{
    counter-increment: num;
    content: counter(num);
    list-style-type: none;
    line-height:25px;
    text-align:center;
}
ul{
    list-style-type: none;
    line-height:50px;
    text-align:center;
}
</style>

  {% if projects|length > 0 %}
    <div class="container mx-auto my-auto py-3 px-1">
    <table class="table table-striped">

      <thead>
        <tr>
          <th style="line-height:20px;text-align:center">#</th>
          <th style="line-height:20px;">Title</th>
          <th style="line-height:20px;text-align:center">Opened By</th>
          <th style="line-height:20px;text-align:center">Opened Date</th>
          <th style="line-height:20px;text-align:center">Priority</th>
          <th style="line-height:20px;text-align:center">Compeleted Date</th>
        </tr>
      </thead>

    {% if issues|length > 0 %}
        {% for issue in issues %}
          <tbody>
            <th style="line-height:20px;text-align:left"><li></li></th>
            <td><a style="line-height:20px;color:blue" class="article-title" href="{{url_for('issues.update_issue', issue_id=issue.id)}}">{{ issue.title }}</a></td>
            <td style="line-height:20px;text-align:center">{{ issue.open_by }}</td>
            <td style="line-height:20px;text-align:center">{{ issue.issue_date.strftime('%Y-%m-%d') }}</td>
            <td style="line-height:20px;text-align:center">{{ issue.priority }}</td>
            <td style="line-height:20px;text-align:center">{{ issue.completed_date}}</td>
            <td><button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#deleteModal_{{issue.id}}">Delete</button></td>
          </tbody>

          <!-- Modal -->
        <div class="modal fade" id="deleteModal_{{ issue.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h6 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this issue?</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <form id="delete_{{ issue.id }}" action="{{ url_for('issues.delete_issue', issue_id=issue.id) }}" method="POST">
                    <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                </form>
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>  
        {% endfor %}
        </table>
    {% else %}
      <div class="alert alert-secondary">No Issues Found</div>
    {% endif %}
  {% else %}
    <div class="alert alert-secondary">No Projects to Add Issues</div>
  {% endif %}
   </div>

{% endblock content %}

service_application_package/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Project - {{ title }}</title>
    {% else %}
        <title>Project Management Service</title>
    {% endif %}
</head>
<body class="body">
    <header class="site-header">
      <nav id="layout_navbar" class="navbar navbar-dark fixed-top navbar-expand-lg">
        <div class="container">
          <a id="home_title" class="navbar-brand mr-4" href="/">Project Management Service</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('projects.list_projects') }}">Projects</a>
              <a class="nav-item nav-link" href="{{ url_for('issues.list_issues') }}">Issues</a>
              <a class="nav-item nav-link" href="{{ url_for('chatroombp.chat') }}">Chat</a>

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
          
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/JavaScript">
      var hostName = window.location.hostname;
      if (hostName.indexOf("dev") > -1 || hostName.indexOf("localhost") > -1) {
          document.getElementById("layout_navbar").style = "background-color: #800000;";
          document.getElementById("home_title").innerText = "Development";
          console.log('development');
      } else  {
          document.getElementById("layout_navbar").style = "background-color: #3C3C3C;";
          document.getElementById("home_title").innerText = "Project Management Service";
      }
    </script>
</body>
</html>

service_application_package/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

service_application_package/templates/projects_all.html
{% extends "layout.html" %}
{% block content %}
  {% if projects|length > 0 %}
    <div class="container mx-auto my-auto py-3 px-1">
      {% for project in projects %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              {% if project.author == current_user %}
                <a class="mr-2" href="{{ url_for('users.user_projects', username=project.author.username) }}">{{ project.author.username }}</a>
                  <small class="text-muted">{{ project.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2>              
                <a class="article-title" href="{{ url_for('projects.update_project', project_id=project.id) }}">{{ project.title }}</a>
              {% else %}
              <div class="mr-2">{{ project.author.username }}</div>
                <small class="text-muted">{{ project.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <h2>              
              <div class="article-title">{{ project.title }}</div>
              {% endif %}
            </h2>
            <div class="row justify-content-between">
              <div class="col">
                <p class="article-content">{{ project.content }}</p>
              </div>
              <div class="col">Percent Complete:
                <p class="article-content">{{ doneList[loop.index0] }}</p>
              </div>
              <div class="col">
                <div class="float-right">
                  <div class="container mx-auto my-auto py-1 px-1">
                    <a class="btn btn-secondary" href="{{ url_for('requirements.list_requirements', project_id=project.id) }}">Requirements</a>
                  </div>
                  {% if project.author  %}
                    <div class="container mx-auto my-auto py-1 px-1">
                      <a class="btn btn-secondary" href="{{ url_for('projects.update_project', project_id=project.id) }}">Update</a>
                    </div>                  
                    <div class="container mx-auto my-auto py-1 px-1">
                      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal_{{ project.id }}">Delete</button>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          </div>
        </article>
        <!-- Modal -->
        <div class="modal fade" id="deleteModal_{{ project.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form id="deleteproject_{{ project.id }}" action="{{ url_for('projects.delete_project', project_id=project.id) }}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
                </form>
              </div>
            </div>
          </div>
        </div>        
      {% endfor %}

    {% else %}
      <div class="alert alert-secondary">No Projects Found</div>
    {% endif %}
      <a id="add-project-btn" class="btn btn-primary" href="{{ url_for('projects.new_project') }}"><strong>Add Project</strong></a>
    </div>
    <!-- projects container -->
  {% endblock content %}

service_application_package/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}